[weeks]

[weeks.wordnet]
key = "wordnet"
nav = "Wordnet"
title = "The Japanese Wordnet and the Open Multilingual Wordnet"
day = "Monday"
time = "16:20–17:50"
room = "Classroom 01"

[weeks.using_wordnets]
key = "using_wordnets"
nav = "Using Wordnets"
title = "Using Wordnets — Online and Through Python"
day = "Wednesday"
time = "13:00–14:30"
room = "Classroom 01"

[weeks.japanese_names]
key = "japanese_names"
nav = "Japanese Names"
title = "An Analysis of Contemporary Japanese Names"
day = "Thursday"
time = "11:20–12:50"
room = "Classroom 4"

[weeks.metonymy]
key = "metonymy"
nav = "Metonymy"
title = "Multilingual Modelling with Wordnets: Metonymy Travels, Metaphor Wanders"
day = "Friday"
time = "10:00–11:30"
room = "JOTA series"
